### PR TITLE
-option disabled_branding  for image without boxbranding

### PR DESCRIPTION
**Pull request by Dima73**
need add flag DOMB_DISABLED_BRANDING

-DOMB_KERNEL_MTD=\"/dev/${MTD_KERNEL}\" \
    -DOMB_DISABLED_BRANDING'
\
    'LDFLAGS= -lfreetype ${LDFLAGS}' \

P.S.I'm not sure what the code is written without errors

### CODE REVIEW

**Comment by dpeddi** [comment]
reallly try this branch...

https://github.com/oe-alliance/openmultiboot/tree/switch_stick_safe

I added some logic to fix your issue

**Comment by Dima73** [comment]
https://github.com/oe-alliance/openmultiboot/commit/e7205c8f3abacdbdec704fe88e1cf118ca338a91
this fix only vu+ box?

**Comment by dpeddi** [comment]
Should fix all boxes.. Maybe we need some improvements for other box

Il 13/gen/2017 08:36 AM, "Dimitrij" <notifications@github.com> ha scritto:

**Comment by dpeddi** [comment]
i will merge the new branch within few days.

your changes arent ok with the new branch

Il 16/gen/2017 11:13, "Dimitrij" <notifications@github.com> ha scritto:

**Pull request closed without merging**
