### PR TITLE
add sleep 3 sec.  for waiting run mdev

### PR DESCRIPTION
**Pull request by Dima73**
When usb connect with hub need add wait

https://github.com/oe-alliance/openmultiboot/issues/21

### CODE REVIEW

**Comment by dpeddi** [comment]
I don't like so much this change... We should add a parameter read from flash and make sleep configurable.. Most boxes don't need the sleep.

**Comment by Dima73** [comment]
# dpeddi
You can make such a patch?

**Comment by arn354** [comment]
How about adding a build-option like allready done for [DOMB_DEFAULT_TIMER](https://github.com/oe-alliance/oe-alliance-core/blob/7b24b3c8b5a09f02d607182f5351d7ef2e49d96d/meta-oe/recipes-oe-alliance/openmultiboot/openmultiboot.bb#L26) using MACHINE_FEATURES?
There at least oe-alliance allready distinguishes between a slow and a faster box. This will basically not be a huge change to [OMB code](https://github.com/oe-alliance/openmultiboot/search?utf8=%E2%9C%93&q=OMB_DEFAULT_TIMER&type=Code)

**Comment by Dima73** [comment]
I did not think that 3 extra second cause such a problem.
I tested three different hub.
And everywhere need a pause.

**Pull request merged**
